# Generated by Django 4.0.3 on 2022-04-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(max_length=3, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
